/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-16 00:31:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.mypage.UserInfo;
import com.kh.mypage.MyPageDAO;

public final class modifyInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.mypage.MyPageDAO");
    _jspx_imports_classes.add("com.kh.mypage.UserInfo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>SHINee Music회원정보수정 페이지</title>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CreateAccountPage.css\">\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"pageColor\">\r\n");
      out.write("            <div class=\"TabColor\"><img src=\"images/mypage.png\" class=\"TabiconImage\"><strong class=\"TabTextStyle\">Modify My Info</strong> \r\n");
      out.write("                <button id=\"pageCloseButton\" class=\"pageCloseButton\" onclick=\"closeButton()\"><Strong class=\"pageCloseButtonText\">X</Strong></button>\r\n");
      out.write("            </div>          \r\n");
      out.write("             \r\n");
      out.write("                <form action=\"ModifyServlet\" method=\"post\" id=\"createAccount\" enctype=\"multipart/form-data\">\r\n");
      out.write("                ");

               
                  //String = id값을 가지고 오겠다.
                  
                  //String userIdValue = request.getParameter("user_id");
                  String id = (String) session.getAttribute("user_id");
                  MyPageDAO mypageDAO = new MyPageDAO();
                  UserInfo userinfo = mypageDAO.getMember(id);
                  
                   
      out.write("\r\n");
      out.write("                <div id=\"divid\">\r\n");
      out.write("                    <label for=\"user_id\">\r\n");
      out.write("                        <img class=\"iconImg\" src=\"images/user.png\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input name=\"user_id\" type=\"text\" value=\"");
      out.print( userinfo.getUserId() );
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("                   \r\n");
      out.write("                    <p id=\"ruleid\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"user_name\">\r\n");
      out.write("                        <img class=\"iconImg\" src=\"images/name.png\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input name=\"user_name\" type=\"text\" value= \"");
      out.print( userinfo.getUserName() );
      out.write("\">\r\n");
      out.write("                    <p id=\"rulename\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"user_password\">\r\n");
      out.write("                        <img class=\"iconImg\" src=\"images/password.png\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input name=\"user_password\" type=\"password\"  oninput=\"pwCheck()\"  value=\"");
      out.print(userinfo.getUserPassword() );
      out.write("\">\r\n");
      out.write("                    <p id=\"rulepm\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"checkpw\">\r\n");
      out.write("                       <img class=\"iconImg\" src=\"images/passwordcheck.png\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input id=\"checkpw\" type=\"password\" oninput=\"pwCheck()\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("                    <span id=\"checkpm\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"user_nickname\">\r\n");
      out.write("                        <img class=\"iconImg\" src=\"images/profile.png\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input name=\"user_nickname\"  type=\"text\" value=\"");
      out.print(userinfo.getUserNickname());
      out.write("\">\r\n");
      out.write("                    <p id=\"rulenickname\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            \r\n");
      out.write("                <div>\r\n");
      out.write("                    <div id=\"profileContainer\">\r\n");
      out.write("                        <!-- 프로필 사진을 표시할 컨테이너 -->\r\n");
      out.write("                        <img id=\"uploadProfile\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label for=\"profileInput\">\r\n");
      out.write("                    <input type=\"file\" id=\"profileInput\" name=\"profileInput\" accept=\"image/jpg\" style=\"margin: 0 0 0 6%;\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <button id=\"profileUploadButton\" type=\"button\">프로필 등록</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"email\">\r\n");
      out.write("                        <img class=\"iconImg\" src=\"images/email.png\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input name=\"email\" type=\"text\" value=\"");
      out.print(userinfo.getEmail() );
      out.write("\">\r\n");
      out.write("                    <p id=\"ruleemail\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"phone_number\">\r\n");
      out.write("                        <img class=\"iconImg\" src=\"images/phone.png\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input name=\"phone_number\" type=\"text\" value=\"");
      out.print(userinfo.getPhoneNumber() );
      out.write("\">\r\n");
      out.write("                    <p id=\"rulephoneNumber\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button id=\"createUserButton\" type=\"submit\"  >정보수정</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.7.1.js\" \r\n");
      out.write("        integrity=\"sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=\" \r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"js/CreateAccountPage.js\">\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
